token = "token"
database_url = "postgres://?????:?????@postgress/??????"
sentry_dsn = ""

[influx] # influxdb 2
url = "http://influx:8086"
token = "influx token"
org = "influx org"
bucket = "influx bucket"